# -*- coding: utf-8 -*-
"""Linear R.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_kezYAycWd0pwN-1v01YMmluv_28Wk7
"""

import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 import seaborn as sns
 import sklearn
 from sklearn.linear_model import LinearRegression
#veri olustur
x=np.random.rand(100,1)
y=3+4*x #y=3+4x

plt.scatter(x,y)

lin_reg = LinearRegression()
lin_reg.fit(x,y)

plt.figure()
plt.scatter(x,y)
plt.plot(x,lin_reg.predict (x),color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Lineer Regression')
plt.show()





